import json
import pathlib

p = pathlib.Path(__file__).resolve().parent.parent / "backend" / "seeds" / "recipes.json"
d = json.loads(p.read_text(encoding="utf-8"))

ru = {
    "Apple cinnamon crumble": "Яблочный крамбл с корицей",
    "Avocado toast": "Тост с авокадо",
    "Bacon and egg breakfast plate": "Завтрак: бекон и яйцо",
    "Baked apples with honey": "Запечённые яблоки с мёдом",
    "Baked cheese pasta": "Запечённая паста с сыром",
    "Baked chicken with potato": "Запечённая курица с картофелем",
    "Banana bread": "Банановый хлеб",
    "Banana oatmeal": "Овсянка с бананом",
    "Basil tomato farfalle": "Фарфалле с базиликом и томатом",
    "Bean salad": "Салат из фасоли",
    "Beef and barley soup style": "Суп с говядиной и перловкой",
    "Beef and mushroom pan": "Говядина с грибами на сковороде",
    "Beef and potato skillet": "Говядина с картофелем",
    "Beef burger patties": "Котлеты для бургера",
    "Beef chili with beans": "Чили кон карне",
    "Beef meatballs in tomato sauce": "Мясные тефтели в томатном соусе",
    "Beef taco bowl": "Тако-боул с говядиной",
    "Berry pancakes": "Оладьи с ягодами",
    "Blueberry compote": "Черничный компот",
    "Breakfast potatoes": "Картофель на завтрак",
    "Broccoli cheddar bake": "Запеканка брокколи с чеддером",
    "Broccoli garlic spaghetti": "Спагетти с брокколи и чесноком",
    "Broccoli salad with yogurt": "Салат из брокколи с йогуртом",
    "Broccoli soup": "Суп из брокколи",
    "Cabbage and carrot slaw": "Салат из капусты и моркови",
    "Cabbage slaw with mayonnaise": "Капустный салат с майонезом",
    "Cabbage soup": "Щи / суп из капусты",
    "Caesar salad style": "Салат Цезарь",
    "Carrot ginger soup style": "Морковный суп с имбирём",
    "Carrot raisin salad": "Морковный салат с изюмом",
    "Cheddar breakfast quesadilla": "Кесадилья с чеддером на завтрак",
    "Cheese omelette": "Сырный омлет",
    "Chicken and rice bowl": "Боул с курицей и рисом",
    "Chicken and rice soup": "Суп с курицей и рисом",
    "Chicken breast with garlic butter": "Куриная грудка с чесночным маслом",
    "Chicken noodle soup": "Куриный суп с лапшой",
    "Chicken pasta skillet": "Паста с курицей на сковороде",
    "Chicken salad with cucumber": "Куриный салат с огурцом",
    "Chicken tomato rice soup": "Суп с курицей, томатом и рисом",
    "Chicken tomato stew": "Тушёная курица с томатом",
    "Chickpea curry with tomato": "Нут карри с томатом",
    "Chickpea salad": "Салат с нутом",
    "Chickpea soup with garlic": "Суп из нута с чесноком",
    "Chocolate banana smoothie": "Шоколадно-банановый смузи",
    "Chocolate brownies": "Шоколадное брауни",
    "Chocolate chip cookies": "Печенье с шоколадной крошкой",
    "Chocolate pudding": "Шоколадный пудинг",
    "Cinnamon honey toast": "Тост с корицей и мёдом",
    "Cinnamon sugar donuts style": "Пончики с корицей и сахаром",
    "Classic pancakes": "Классические блины",
    "Cocoa mug cake": "Какао-кекс в кружке",
    "Corn and tomato salad": "Салат с кукурузой и томатом",
    "Cottage cheese bowl": "Творожный боул",
    "Creamy corn soup": "Сливочный суп из кукурузы",
    "Creamy mushroom spaghetti": "Сливочные спагетти с грибами",
    "Creamy tomato penne": "Сливочная пенне с томатом",
    "Creamy tomato soup": "Сливочный томатный суп",
    "Cucumber yogurt salad": "Салат из огурца с йогуртом",
    "Egg salad": "Яичный салат",
    "Egg sandwich": "Бутерброд с яйцом",
    "Eggplant tomato sauté": "Тушёные баклажаны с томатом",
    "Eggs and spinach toast": "Тост с яйцом и шпинатом",
    "Farfalle pesto": "Фарфалле с песто",
    "French toast": "Французские тосты",
    "Garlic butter pasta": "Паста с чесночным маслом",
    "Garlic mushroom toast": "Тост с грибами и чесноком",
    "Greek salad": "Греческий салат",
    "Honey garlic chicken": "Курица с мёдом и чесноком",
    "Lemon honey sorbet style": "Лимонный сорбет с мёдом",
    "Lemon parmesan spaghetti": "Спагетти с лимоном и пармезаном",
    "Lemon yogurt cake": "Йогуртовый кекс с лимоном",
    "Lentil soup": "Суп из чечевицы",
    "Lentil stew with carrot": "Чечевица с морковью",
    "Minestrone style soup": "Минестроне",
    "Mushroom risotto style": "Грибное ризотто",
    "Mushroom soup": "Грибной суп",
    "Oatmeal with honey and cinnamon": "Овсянка с мёдом и корицей",
    "Pasta carbonara style": "Паста карбонара",
    "Peas and rice pilaf": "Плов с горошком",
    "Penne arrabbiata": "Пенне арабьята",
    "Pork and cabbage stir-fry": "Свинина с капустой",
    "Pork chops with mustard sauce": "Свиные отбивные с горчичным соусом",
    "Pork with garlic and soy sauce": "Свинина с чесноком и соевым соусом",
    "Potato and broccoli soup": "Суп с картофелем и брокколи",
    "Potato and egg salad": "Картофельный салат с яйцом",
    "Potato and mushroom sauté": "Картофель с грибами",
    "Potato leek soup style": "Суп с картофелем и луком-пореем",
    "Potato salad": "Картофельный салат",
    "Rice pudding": "Рисовый пудинг",
    "Roasted vegetables tray": "Запечённые овощи",
    "Salmon salad": "Салат с лососем",
    "Sausage and bell pepper skillet": "Колбаски с перцем",
    "Sausage rice skillet": "Рис с колбасками",
    "Sausage tomato penne": "Пенне с колбасками и томатом",
    "Scrambled eggs with butter": "Яичница-болтунья",
    "Shrimp garlic spaghetti": "Спагетти с креветками и чесноком",
    "Simple garden salad": "Простой овощной салат",
    "Simple pancakes with honey": "Простые блины с мёдом",
    "Simple sugar cookies": "Простое сахарное печенье",
    "Spaghetti tomato basil": "Спагетти с томатом и базиликом",
    "Spinach omelette": "Шпинатный омлет",
    "Spinach ricotta penne": "Пенне со шпинатом и рикоттой",
    "Spinach salad with feta": "Салат со шпинатом и фетой",
    "Spinach soup with egg": "Суп со шпинатом и яйцом",
    "Strawberry compote": "Клубничный компот",
    "Strawberry yogurt parfait": "Клубничный йогуртовый парфе",
    "Tomato and cabbage soup": "Томатный суп с капустой",
    "Tomato basil eggs": "Яйца с томатом и базиликом",
    "Tomato basil pasta salad": "Паста-салат с томатом и базиликом",
    "Tomato basil soup": "Томатный суп с базиликом",
    "Tomato cucumber breakfast salad": "Салат с томатом и огурцом",
    "Tomato cucumber salad bowl": "Салат с томатом и огурцом",
    "Tomato mozzarella bake": "Запеканка с томатом и моцареллой",
    "Tomato mozzarella salad": "Салат с томатом и моцареллой",
    "Tomato tuna pasta": "Паста с тунцом и томатом",
    "Tuna salad": "Салат с тунцом",
    "Turkey-style meat patties": "Котлеты из индейки",
    "Vanilla cupcakes": "Ванильные капкейки",
    "Vegetable fried rice": "Жареный рис с овощами",
    "Vegetable pasta primavera": "Паста с овощами по-весеннему",
    "Vegetable soup with beans": "Овощной суп с фасолью",
    "Vegetable soup with potato": "Овощной суп с картофелем",
    "Vegetarian chili with beans": "Вегетарианское чили",
    "Vegetarian pasta with tomato and spinach": "Вегетарианская паста с томатом и шпинатом",
    "Walnut honey bars": "Батончики с грецким орехом и мёдом",
    "Warm mushroom salad": "Тёплый грибной салат",
    "Yogurt and banana bowl": "Йогурт с бананом",
    "Yogurt bowl with berries": "Йогурт с ягодами",
    "Zucchini garlic sauté": "Кабачки с чесноком",
}

def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')

out_dir = pathlib.Path(__file__).resolve().parent / "internal" / "handler"
lines = [
    "// Code generated by gen_titles.py from backend/seeds/recipes.json; DO NOT EDIT.",
    "",
    "package handler",
    "",
    "func init() {",
]
for t in sorted({x["title"].strip() for x in d}):
    key = t.lower()
    r = ru.get(t, t)
    lines.append(f'\trecipeTitleENToRU["{esc(key)}"] = "{esc(r)}"')

for k, v in (
    ("pizza", "пицца"),
    ("pasta", "паста"),
    ("omelette", "омлет"),
    ("soup", "суп"),
    ("salad", "салат"),
):
    lines.append(f'\trecipeTitleENToRU["{esc(k)}"] = "{esc(v)}"')

lines.append("}")

out_path = out_dir / "recipe_title_ru_generated.go"
out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("wrote", out_path)
